### ISSUE TITLE
Add serial port support in js side

### ISSUE THREAD

**Issue by topelinux** [marcelkottmann/esp32-javascript#2]
I notice there is gpio support in javascript side,but serial port is missing in Javascript side, it would be great if it could be added.

**Comment by marcelkottmann** [comment]
Hi @topelinux , sorry I was on vacation the last weeks. I will look into it as soon as possible.

Do you refer to the Arduino `Serial` interface, so that this is exposed into the JS context?

**Comment by topelinux** [comment]
Yes

**Comment by marcelkottmann** [comment]
Wow that was a fast reply :-) Ok I will look into it.

**Comment by marcelkottmann** [comment]
I looked into this and my opinion about it is, that the core is not the right
place for reconstructing the whole Arduino API in JavaScript.

I will instead give some advice on how you can create c/c++ bindings for the
needed methods by yourself.

Here is a (tested) example for Serial.begin, Serial.println and Serial.availableForWrite:

1. Create a file named `project.cpp` in the `./main` directory

2. Implement the esp32_javascript_main callback function inside this `project.ccp`:

```c
#include <duktape.h>
#include "HardwareSerial.h"

static duk_ret_t Serial_begin(duk_context *ctx)
{
    unsigned long speed = duk_to_uint(ctx, 0);
    Serial.begin(speed);
    return 0; // 0 means, that it returns undefined
}

static duk_ret_t Serial_availableForWrite(duk_context *ctx)
{
    int avail = Serial.availableForWrite();
    duk_push_int(ctx, avail);
    return 1; // 1 means, that it has a return value
}

static duk_ret_t Serial_println(duk_context *ctx)
{
    const char *message = duk_to_string(ctx, 0);
    Serial.println(message);
    return 0; // 0 means, that it returns undefined
}

static void bind_Serial(duk_context *ctx)
{
    duk_push_object(ctx);
    duk_push_c_function(ctx, Serial_begin, 1); // 1 means, that it has one argument
    duk_put_prop_string(ctx, -2, "begin");
    duk_push_c_function(ctx, Serial_availableForWrite, 0); // 0 means, that it has no arguments
    duk_put_prop_string(ctx, -2, "availableForWrite");
    duk_push_c_function(ctx, Serial_println, 1); // 1 means, that it has one argument
    duk_put_prop_string(ctx, -2, "println");
    duk_put_global_string(ctx, "Serial");
}

extern void esp32_javascript_main(duk_context *ctx)
{
    bind_Serial(ctx);
}
```

Then you can use following JavaScript code to print on Serial:

```JavaScript
Serial.begin(115200);
Serial.println('Hello world!');
```

You may want to use the script `https://raw.githubusercontent.com/marcelkottmann/esp32-javascript/master/examples/repl.js`, which can help you to
evaluate the JavaScript API 'on-the-fly'. You can configure this as 'JS URL' in the '/setup'.

**Comment by topelinux** [comment]
OK, thanks for your reply
i think, i could add serial support following above guide

Just curious, from long term view, do you think `serial support` will included in the `Core`
