### ISSUE TITLE
Add OTA-update for Firmware

### ISSUE THREAD

**Issue by v6racer** [marcelkottmann/esp32-javascript#9]
Is it possible to add an OTA update of the firmware to the project? The firmware could then be updated remotely. If you have C-Bindigs that you want to expand, OTA would be a useful extension.

**Comment by marcelkottmann** [comment]
Hi @v6racer, thanks for your interest. I am currently in the process of improving some of the implementation, so native OTA will be available soon. However, I just started working on it last week and can only work on it in my spare time. I guess it will take a few more weeks (~4 weeks). I will keep this issue open to track the progress.

**Comment by v6racer** [comment]
Thank you for the quick and positive response. 
The project is a great idea. I want to use it for an automation project.

**Comment by marcelkottmann** [comment]
Hi @v6racer ,

I have been able to work on native OTA and have prepared a first stable version on the branch
`native-ota`

You can perform a native firmware OTA upgrade by calling the URL /setup . There is a new section called "Native OTA" where you can provide two urls to the new images: One for the actual firmware image (normally named esp32-javascript.bin in your build directory) and the other for the JS modules image (normally named modules.bin in your build directory).

The upgrade is performed in the background, that means, while loading the new images, you can navigate back and look into the new log file section.

You can check the upgrade status either by staying on the upgrade page, which is reloaded automatically every ~20 seconds or click on Upgrade status in the Setup page.

After upgrade has finished you have to restart the device to load the new firmware.

I would be happy if you could test the new feature and give me feedback on it.

**Comment by v6racer** [comment]
Hi @marcelkottmann,

thanks for the quick feedback and the new version with OTA. 
The earliest I can test it is next week. But I will test it and give feedback as soon as I can.

Does the URL (for the images) have to be a web server or can it also be a local store (file://)?

**Comment by marcelkottmann** [comment]
Hi @v6racer , No it has to be a http or https protocol URL. But you can easily start a local webserver serving local files with 
`npx http-server [dir] --port 8080`

**Comment by v6racer** [comment]
Sorry for my late feedback.
I have made a first short test. The update works without problems.
Thanks for the great work.

**Comment by marcelkottmann** [comment]
Finally merged https://github.com/marcelkottmann/esp32-javascript/pull/10
